### ISSUE TITLE
Correção no item 3.7 do cap. 3

### ISSUE THREAD

**Issue by eduardolfalcao** [ufpb-computacao/introducao-a-ead-livro#3]
Uma pequena falha no "LivroTextoCapitulo3.pdf"
No ítem 3.7 Recapitulando, tem: "Uso da tecnologia da comunicação e da informação e,"
Acredito que a finalização deste trecho ficou incompleto.

**Comment by edusantana** [comment]
@ufpbvirtual Desculpe ter demorado tanto tempo para responder.

Favor verificar se na última versão o erro persiste: 
https://github.com/edusantana/introducao-a-ead-livro/releases/tag/v1.0.2
